# Generated by Django 5.0.1 on 2024-01-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_student_user_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmarks',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentmarks', to='home.student'),
        ),
    ]
